### ISSUE TITLE
After switch to blockcyper, now can create a new chat, but cannot send message or show chat

### ISSUE THREAD

**Issue by stoicism2323** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#29] opened 2016-05-08 22:34 UTC
So now I can get past 'dropzone chat new', and it successfully returns a transactionid to use for chat.

However, after trying 'dropzone chat say' or 'dropzone chat show' with that returned txid, I get an error:

[@localhost dropzone-ruby]$ ./bin/dropzone chat show $privaddr $(cat chatsession.txt )

> error: 404 Resource Not Found: {"status":"fail","data":null,"code":404,"message":"No records found"}. Use --trace to view backtrace

--trace shows that it fails in blockrio_ext.rb:74:in `getrawtransaction'

Thanks for the last fix and forgive me if I'm being stupid at some point here. Thanks!

**Comment by stoicism2323** [comment] 2016-05-08 22:44
It looks like the call to getrawtransaction from dropzone-ruby/lib/blockrio_ext.rb (called by both chat say and chat show) calls into counterparty blockr_io.rb, which just uses blockr.io. Is there a way to get counterpartylib to use blockcypher instead? Thanks!

**Comment by ScroogeMcDuckButWithBitcoin** [comment] 2016-05-09 02:07
can you run a ./bin/dropzone listing show 6a9013b8684862e9ccfb527bf8f5ea5eb213e77e3970ff2cd8bbc22beb7cebfb and see if that works? 

Additionally, can you run the reported command (the chat show command) with a "RESTCLIENT_LOG=stdout " prepended to the "./bin/dropzone" , and report that here? It should show me more info on why that's failing. 

I don't mind re-writing to use blockcypher, though probably this ruby code should just handle drivers the way that the javascript code does...

**Comment by stoicism2323** [comment] 2016-05-09 22:17
That dz listing show command works and shows the listing of the bible.

The chat show command with RESTCLIENT_LOG=stout prepended shows the following output:

```
RestClient.get "http://tbtc.blockr.io/api/v1/tx/raw/89b2ae96e1017d07d1b6a33fdbdc252336546f48b679a5723ffb794f5ca67979", "Accept"=>"*/*; q=0.5, application/xml", "Accept-Encoding"=>"gzip, deflate", "Content-Type"=>"application/json"
# => 404 NotFound | application/json 69 bytes
error: 404 Resource Not Found: {"status":"fail","data":null,"code":404,"message":"No records found"}. Use --trace to view backtrace
```

Thanks

**Comment by ScroogeMcDuckButWithBitcoin** [comment] 2016-05-21 22:29
Care to try now? I have a patchy version of this working. Here's the reason for the issue: https://github.com/bitcoin/bitcoin/issues/8079 It's not a bug in dropzone per-se, it's a change to what the newest bitcoind's are relaying by default. 

There's a number of good fixes, but I'm waiting to see what @rubensayshi wants to do with Counterparty before implementing them. In the meantime, I'm using blockcypher as a relay, since they're on an older bitcoind. (I'm sure they'll upgrade at some point though, so let's see what happens with that issue)

**Comment by stoicism2323** [comment] 2016-05-22 00:05
Wow, it works now! What exactly changed? I didn't have to update any projects

**Comment by stoicism2323** [comment] 2016-05-23 23:21
So it looks like the chat messages can be sent (the chat say command does not return failure) but when I try to show the chat message from either the perspective of the sender or the recipient, I get a blank message:

$ ./bin/dropzone chat show $(cat ~/tnwallet2.txt | sed -n 1p) $(cat chatses2.txt )
+------------------------------------------------------------------------+
| Chat: c17fbfc1693f03c104072c30a092301c97d2293bd6e40e0f5d0eb20b8345e9d6 |
+------------------------------------------------------------------------+
+------------------------------------------------------------------------+
$ ./bin/dropzone chat show $(cat ~/tnwallet.txt | sed -n 1p) $(cat chatses2.txt )
+------------------------------------------------------------------------+
| Chat: c17fbfc1693f03c104072c30a092301c97d2293bd6e40e0f5d0eb20b8345e9d6 |
+------------------------------------------------------------------------+
+------------------------------------------------------------------------+

This transaction is valid, and it seems to be pointed to the right addresses:
http://tbtc.blockr.io/tx/info/c17fbfc1693f03c104072c30a092301c97d2293bd6e40e0f5d0eb20b8345e9d6

Thanks for all your help with this issue!

**Comment by ScroogeMcDuckButWithBitcoin** [comment] 2016-06-05 19:42
Well,  for the time being I decided to revert to pubkeyhash encoding when neeeded. Care to try and test that for me? If it works, I'll close this issue, and keep working through the bare multisig politics

**Comment by stoicism2323** [comment] 2016-06-05 22:23
Looks like messages are getting successfully relayed and written.

However, I am running into an issue where I have two conversations open <chat1> and <chat2>, both between <addr1> and <addr2>, and whenever either addr1 or addr2 sends to either of the open chats, the chat message appears in both chats. Looks like however that when I open a third chat between addr1 and addr3, this one is not viewable by addr2.

[@localhost dropzone-ruby]$ dz chat list $(cat tnwallet3.txt | sed -n 1p)
+---------------------------------------------------------------------------+
| Session: a66c4fa830ce1126628f4eff5346bcdac1be23e9a270c213999ae0c3ea06a2bc |
+---------------------------------------------------------------------------+
| Address : mtpoiodUv7frnEajxTQ4e64MGBp79rfnYD                              |
| Messages: 0 Unread / 4 Total                                              |
+---------------------------------------------------------------------------+
+---------------------------------------------------------------------------+
| Session: fcc9a3d525bbbd914622190ea0dc0639f4e5806a2e9952bed43ef18aa9e96945 |
+---------------------------------------------------------------------------+
| Address : mtpoiodUv7frnEajxTQ4e64MGBp79rfnYD                              |
| Messages: 0 Unread / 4 Total                                              |
+---------------------------------------------------------------------------+

It seems like session a66c... and fcc9... both contain the same messages. Messaging a66c... is the same as messaging fcc9.

There is also an issue that shows up depending on the inbox state which shows negative numbers for 'unread' message count.

Otherwise sending messages now works well :)

**Comment by ScroogeMcDuckButWithBitcoin** [comment] 2016-06-06 15:31
It might be that your ~/.dropzone/dropzone.db or .dropzone/cache.db is in a weird state, given the issues prior. Can you remove those files and try again? Note that if you remove those files, you'll lose your shared secrets...

**Comment by stoicism2323** [comment] 2016-06-06 19:30
You mean you'll lose the contents of the chat sessions (the chat messages)? Wouldn't those messages be rebuildable from the testnet blockchain? Thanks

**Comment by ScroogeMcDuckButWithBitcoin** [comment] 2016-06-12 19:06
A private key is generated by both parties. A symmetric key is negotiated between them thereafter. The generated private key, is kept in this file, and this key is unique to each chat session between addresses. So while the data is on the blockchain, without this key - the data is meaningless.

**Closed as completed by ScroogeMcDuckButWithBitcoin** 2016-06-12 19:06 UTC
